# Basic config for the Bitvavo bot
quote: EUR
symbols: [BTC, ETH, ADA, SOL, XRP]
timeframe: "15m"
sma_fast: 20
sma_slow: 50

# Risk and sizing
fixed_stake_quote: 0
stake_fraction: 0.05

# Position constraints
max_open_positions: 50
max_pct_per_coin: 2
only_buy_if_not_in_position: true
single_open_buy_per_coin: true
cooldown_minutes: 30

# Sell logic
sell_enabled: false
take_profit_pct: 0
stop_loss_pct: 0

# Loop
sleep_seconds: 60
