[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "ccxt==4.4.37",
    "flask==3.1.0",
    "pandas==2.2.3",
]
